### PR TITLE
Resolve Bounty 27

### PR DESCRIPTION
**Pull request by MaxMustermann2**
[Bounty Link](https://github.com/harmony-one/bounties/issues/27)

Changes include:
- Allow all Solidity versions (see [here](https://github.com/MaxMustermann2/harmony-contract-code-verification-tool/blob/a0d902b1543dcdf20f0ec21539b6fb60b54861eb/src/verification/verify.ts) for details)
- Create command line interface (defined in the README)
- Add tests (coverage noted in the README)
- Add build, run and test instructions to README with sample output
- Prettify the output

### CODE REVIEW

**Review by rac-sri — COMMENTED** [review]
Failing for 
```yarn start verify --contractAddress one16jnqg9jxwn4uqezwgwq0gaht8kz3tveuzp8q0t --githubURL https://github.com/rachit2501/ReFungible-Nft/blob/main/contracts/ReFungibleNFT.sol --chainType testnet --solidityVersion 0.8.0```
Compiler has optimization set to ```true```, and runs set to 200.

**Comment by MaxMustermann2** [comment]
> Failing for
> `yarn start verify --contractAddress one16jnqg9jxwn4uqezwgwq0gaht8kz3tveuzp8q0t --githubURL https://github.com/rachit2501/ReFungible-Nft/blob/main/contracts/ReFungibleNFT.sol --chainType testnet --solidityVersion 0.8.0`
> Compiler has optimization set to `true`, and runs set to 200.

Hi @rachit2501, thanks for flagging. I fixed this.

**Comment by rac-sri** [comment]
> > Failing for
> > `yarn start verify --contractAddress one16jnqg9jxwn4uqezwgwq0gaht8kz3tveuzp8q0t --githubURL https://github.com/rachit2501/ReFungible-Nft/blob/main/contracts/ReFungibleNFT.sol --chainType testnet --solidityVersion 0.8.0`
> > Compiler has optimization set to `true`, and runs set to 200.
> 
> Hi @rachit2501, thanks for flagging. I fixed this.

I am still getting result verified:false . I can assure you the above details, contract address, sol file, solc version are accurate. The compiler do had optimization set to true as mentioned above. Maybe you can send me the exact command which includes setting optimization ?

**Comment by MaxMustermann2** [comment]
The contract repository is missing the dependency files, and thus compilation fails (unless you have them installed globally). After adding a `package.json` the below seems to work. I have filed a PR above to include it in your master repository. 
```bash
yarn start verify --contractAddress one16jnqg9jxwn4uqezwgwq0gaht8kz3tveuzp8q0t --githubURL https://github.com/MaxMustermann2/ReFungible-Nft/blob/main/contracts/ReFungibleNFT.sol --chainType testnet --solidityVersion 0.8.0
```
Output
```bash
yarn run v1.22.10
$ cd dist && node index.js verify --contractAddress one16jnqg9jxwn4uqezwgwq0gaht8kz3tveuzp8q0t --githubURL https://github.com/MaxMustermann2/ReFungible-Nft/blob/main/contracts/ReFungibleNFT.sol --chainType testnet --solidityVersion 0.8.0
✔ Got actual bytecode from the blockhain
✔ Github repository cloned
✔ Truffle configuration ready
✔ Contract dependencies installed
✔ Compiling complete
✔ Obtained compiled bytecode
✔ Cloned repository deleted
┌────────────┬────────────────────────────────────────────┐
│  (index)   │                   Values                   │
├────────────┼────────────────────────────────────────────┤
│  verified  │                    true                    │
│ commitHash │ '23231f46f48b1c05081a0ad8986adf0933f53500' │
└────────────┴────────────────────────────────────────────┘
Done in 120.70s.
```

**Comment by MaxMustermann2** [comment]
I have added error handling for this use case (as well as another one where there's no `sol` contract file in the repo). Now, running the command `yarn start verify --contractAddress one16jnqg9jxwn4uqezwgwq0gaht8kz3tveuzp8q0t --githubURL https://github.com/rachit2501/ReFungible-Nft/blob/main/contracts/ReFungibleNFT.sol --chainType testnet --solidityVersion 0.8.0` should give the following result:
```bash
✔ Got actual bytecode from the blockhain
✔ Github repository cloned
✔ Truffle configuration ready
✔ Contract dependencies installed
✖ Compilation was not successful
✔ Cloned repository deleted
┌──────────┬─────────────────────────────────────────────────────┐
│ (index)  │                       Values                        │
├──────────┼─────────────────────────────────────────────────────┤
│ verified │                        false                        │
│  error   │ 'Compilation failed; please check for dependencies' │
└──────────┴─────────────────────────────────────────────────────┘
```

**Comment by rac-sri** [comment]
Looks good. Let me do some more testing and get back to you.

**Pull request merged**
